//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polar.Samples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polar.Samples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Polar.Common;
        ///using Polar.DB;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Polar.Samples
        ///{
        ///    public class Demo101 : ISample
        ///    {
        ///        public ICollection&lt;IField&gt; Fields { get; set; }
        ///
        ///        //START_SOURCE_CODE
        ///        public void Run()
        ///        {
        ///            Console.WriteLine(&quot;Start Demo101&quot;);
        ///            // === Демонстрация базовых действий со структурами ===
        ///            // Соз [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Demo101 {
            get {
                return ResourceManager.GetString("Demo101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Polar.Common;
        ///using Polar.DB;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Polar.Samples
        ///{
        ///    public class Demo102 : ISample
        ///    {
        ///        public ICollection&lt;IField&gt; Fields { get; set; }
        ///        //START_SOURCE_CODE
        ///        public void Run()
        ///        {
        ///            Console.WriteLine(&quot;Start Demo201: work with bearing sequence&quot;);
        ///            System.Diagnostics.Stopwatch sw = new System.Diag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Demo102 {
            get {
                return ResourceManager.GetString("Demo102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Polar.Common;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Polar.Samples.Index
        ///{
        ///    public class Sample3 : ISample
        ///    {
        ///        public ICollection&lt;IField&gt; Fields { get; set; }
        ///
        ///        public void Run()
        ///        {
        ///
        ///        }
        ///        public string Name { get; set; }
        ///        public string DiplayName { get =&gt; &quot;Sample3&quot;; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Demo103 {
            get {
                return ResourceManager.GetString("Demo103", resourceCulture);
            }
        }
    }
}
